name: Ejecutar pruebas Selenium en cada push

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  selenium-tests:
    runs-on: ubuntu-latest

    env:
      URL_ADMIN_LOGIN: ${{ secrets.URL_ADMIN_LOGIN }}
      MY_APP_EMAIL_ADMIN: ${{ secrets.MY_APP_EMAIL_ADMIN }}
      MY_APP_PASSWORD_ADMIN: ${{ secrets.MY_APP_PASSWORD_ADMIN }}

      URL_SELLER_LOGIN: ${{ secrets.URL_SELLER_LOGIN }}
      MY_APP_EMAIL_SELLER: ${{ secrets.MY_APP_EMAIL_SELLER }}
      MY_APP_PASSWORD_SELLER: ${{ secrets.MY_APP_PASSWORD_SELLER }}

      URL_CUSTOMER_LOGIN: ${{ secrets.URL_CUSTOMER_LOGIN }}
      MY_APP_EMAIL_CUSTOMER: ${{ secrets.MY_APP_EMAIL_CUSTOMER }}
      MY_APP_PASSWORD_CUSTOMER: ${{ secrets.MY_APP_PASSWORD_CUSTOMER }}

      MY_APP_EMAIL_INCORRECT: ${{ secrets.MY_APP_EMAIL_INCORRECT }}
      MY_APP_PASSWOR_INCORRECT: ${{ secrets.MY_APP_PASSWOR_INCORRECT }}

      MJ_APIKEY_PUBLIC: ${{ secrets.MJ_APIKEY_PUBLIC }}
      MJ_APIKEY_PRIVATE: ${{ secrets.MJ_APIKEY_PRIVATE }}
      SENDER_EMAIL: ${{ secrets.SENDER_EMAIL }}
      RECIPIENT_EMAIL: ${{ secrets.RECIPIENT_EMAIL }}

    steps:
      - name: Clonar repositorio
        uses: actions/checkout@v4

      - name: Instalar Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Instalar dependencias
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Ejecutar pruebas Selenium
        run: |
          python pruebas/cp01.py
          # Si necesitas ejecutar otros scripts:
          # python pruebas/cp02.py
          # python pruebas/cp03.py
